#!/usr/bin/env python3
"""
Quadratic Maximum Likelihood (QML) Power Spectrum Estimation Pipeline.

This script provides the main entry point for QML power spectrum estimation
using the CosmoForge framework. The QML method provides optimal, unbiased
power spectrum estimates from CMB observations by accounting for sky cuts,
inhomogeneous noise, and instrumental effects through exact likelihood analysis.

The QML estimator computes power spectrum amplitudes as:
q̂_l = (1/2) * x^T * E_l * x

where E_l = C^(-1) * ∂C/∂q_l * C^(-1) is the quadratic estimator matrix,
x is the observed data vector, and C is the total covariance matrix.
The estimates are then optimally combined using the Fisher information matrix.

Features:
- Optimal statistical properties (minimum variance, unbiased)
- Exact treatment of sky cuts and noise inhomogeneity
- MPI-parallelized computation for scalability
- Support for auto-correlation and cross-correlation analyses
- Noise bias computation and optional subtraction
- Integration with Fisher matrix error propagation

Usage:
    # Serial execution
    python main_qml.py

    # MPI parallel execution
    mpirun -n 8 python main_qml.py

Configuration:
    Analysis parameters are read from the YAML configuration file specified
    in the Spectra class initialization. Key parameters include:
    - Map file paths and format specifications
    - Covariance matrix file paths (from Fisher analysis)
    - Monte Carlo simulation settings
    - Cross-correlation vs auto-correlation mode
    - Noise bias handling options

Input Requirements:
    The QML analysis requires several input files typically generated by
    prior Fisher matrix computation:
    - Observational maps in HEALPix FITS format
    - Inverted covariance matrices from Fisher analysis
    - Beam transfer functions and power spectra
    - Sky masks and active pixel definitions

Output Files:
    - Power spectrum estimates for all simulations
    - Noise bias terms (auto-correlation only)
    - Error bars from Fisher matrix propagation
    - QML covariance matrices for error analysis

Computational Notes:
    QML estimation is computationally intensive, scaling as O(N_pix^3) for
    E-operator computation and O(N_ell * N_pix^2 * N_sims) for quadratic
    evaluations. Memory usage is dominated by covariance matrix storage.

See Also:
    main_fisher.py : Fisher matrix computation required for QML normalization
    produce_mock_inputs.py : Generate synthetic observations for testing

References:
    .. [1] Tegmark, M. "How to measure CMB power spectra without losing
       information" Phys. Rev. D 55, 5895 (1997)
    .. [2] Bond, J.R., Jaffe, A.H. & Knox, L. "Estimating the power spectrum of
       the cosmic microwave background" Phys. Rev. D 57, 2117 (1998)
    .. [3] Oh, S.P., Spergel, D.N. & Hinshaw, G. "An efficient technique to
       determine the power spectrum from cosmic microwave background sky maps"
       Astrophys. J. 510, 551 (1999)
"""

from qube.spectra import Spectra


def main():
    """
    Execute QML power spectrum estimation pipeline.

    This function orchestrates the complete QML analysis workflow including
    data loading, Fisher matrix processing, E-operator computation, and
    parallel quadratic likelihood evaluation. The function handles MPI
    coordination automatically and produces optimally-weighted power
    spectrum estimates.

    The analysis pipeline consists of:
    1. Parameter file parsing and validation
    2. Map data loading and preprocessing
    3. Fisher matrix inversion with normalization
    4. Parallel E-operator computation for each multipole
    5. Quadratic form evaluation for all simulations
    6. Fisher matrix combination for final estimates

    The pipeline can operate in two modes:
    - Auto-correlation: Single dataset with noise bias computation
    - Cross-correlation: Independent datasets (naturally noise-bias free)

    Results are available only on the master process (rank 0) and include:
    - Optimally-weighted power spectrum estimates
    - Noise bias terms (auto-correlation mode only)
    - Statistical error bars from Fisher matrix propagation

    Raises:
        FileNotFoundError: If input files (maps, covariance matrices) not found
        ValueError: If Fisher matrix is singular or parameters inconsistent
        MPIError: If MPI communication fails during parallel computation

    Notes:
        The function uses a hardcoded configuration file path. For production
        use, consider making this configurable via command line arguments.

        Memory usage scales with map resolution and number of simulations.
        The computation requires substantial memory for covariance matrix
        storage and manipulation.

    Examples:
        Serial execution:
        >>> main()  # Uses default configuration file

        MPI execution (from command line):
        $ mpirun -n 8 python main_qml.py
    """
    # Initialize QML power spectrum estimation with configuration file
    # TODO: Consider making config file path configurable via command line
    qml_analyzer = Spectra("src/cosmoforge.qube/qube/TEB_defaults.yaml")
    logger = qml_analyzer.logger

    logger.info("Initializing QML power spectrum estimation...")

    # Execute the complete QML analysis pipeline
    # This includes Fisher computation (if needed), map loading, and QML estimation
    logger.info("Starting QML analysis pipeline...")
    qml_analyzer.run()

    # Retrieve and display results (only available on master process)
    power_spectra = qml_analyzer.get_power_spectra()
    if power_spectra is not None:
        logger.info("=" * 60)
        logger.info("QML POWER SPECTRUM ESTIMATION COMPLETED SUCCESSFULLY")
        logger.info("=" * 60)
        logger.log_matrix_info("Power spectra", power_spectra, level=1)
        logger.info(f"Number of simulations: {power_spectra.shape[0]}")
        logger.info(f"Number of parameters: {power_spectra.shape[1]}")

        # Display statistical summary of power spectrum estimates
        mean_spectra = power_spectra.mean(axis=0)
        std_spectra = power_spectra.std(axis=0)
        logger.log_with_feedback("\nPower spectrum statistics:", 3)
        mean_range = f"[{mean_spectra.min():.3e}, {mean_spectra.max():.3e}]"
        std_range = f"[{std_spectra.min():.3e}, {std_spectra.max():.3e}]"
        logger.log_with_feedback(f"Mean amplitude range: {mean_range}", 3)
        logger.log_with_feedback(f"Standard deviation range: {std_range}", 3)

        # Display first few multipoles as examples
        logger.log_with_feedback("\nFirst 5 multipole estimates (mean ± std):", 3)
        for i in range(min(5, len(mean_spectra))):
            logger.log_with_feedback(
                f"  Parameter {i + 1}: {mean_spectra[i]:.3e} ± {std_spectra[i]:.3e}",
                3,
            )

        # Handle noise bias for auto-correlation analyses
        if not qml_analyzer.params.do_cross:
            noise_bias = qml_analyzer.get_noise_bias()
            if noise_bias is not None:
                logger.info("\nNoise bias computed successfully:")
                logger.log_matrix_info("Noise bias", noise_bias, level=2)
                logger.log_with_feedback(f"Mean bias level: {noise_bias.mean():.3e}", 3)

                # Show bias significance relative to signal
                bias_significance = abs(noise_bias / mean_spectra)
                bias_percent = bias_significance.mean()
                logger.info(f"Bias significance (|bias/signal|): {bias_percent:.2%}")
            else:
                logger.warning("Warning: Could not compute noise bias")
        else:
            logger.info("\nCross-correlation analysis: noise bias not applicable")
    else:
        logger.info("QML computation completed (worker process)")

    logger.info("\nAnalysis complete. Check output files for detailed results.")


if __name__ == "__main__":
    main()
